version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists..."
      - apt-get update -y
      - echo "Installing Node.js 20.x..."
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - node -v
      - npm -v
      - echo "Installing Java 17 (OpenJDK)..."
      - apt-get install -y openjdk-17-jdk
      - java -version
      - echo "Installing Angular CLI globally..."
      - npm install -g @angular/cli

  pre_build:
    commands:
      - echo "Installing backend dependencies..."
      - cd Finance-Backend
      - chmod +x mvnw
      - ./mvnw clean install -DskipTests
      - cd ../Finance-Frontend
      - echo "Installing frontend dependencies..."
      - npm install
      - cd ..

  build:
    commands:
      - echo "Building Angular app..."
      - cd Finance-Frontend
      - npm run build -- --output-path=../build/frontend
      - cd ../Finance-Backend
      - echo "Building Spring Boot app..."
      - ./mvnw clean package -DskipTests
      - mkdir -p ../build/backend
      - cp target/*.jar ../build/backend/app.jar
      - cd ..

  post_build:
    commands:
      - echo "Build completed successfully."
      - ls -R build

artifacts:
  files:
    - frontend/**
    - backend/app.jar
    - appspec.yml
    - scripts/**
  base-directory: build
