version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 20
    commands:
      - echo Installing backend and frontend...
      - cd Finance-Backend
      - chmod +x mvnw
      - ./mvnw clean install -DskipTests
      - cd ../Finance-Frontend
      - npm install

  build:
    commands:
      - echo Building Angular app...
      - npm run build -- --output-path=../build/frontend
      - cp ../Finance-Backend/target/*.jar ../build/backend/app.jar

artifacts:
  files:
    - '**/*'
  base-directory: build
