version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17
    commands:
      - echo "Installing n (Node version manager)..."
      - npm install -g n
      - echo "Installing Node.js 20.19.0..."
      - n 20.19.0
      - export PATH="/usr/local/n/versions/node/20.19.0/bin:$PATH"
      - node -v
      - npm -v
      - echo "Installing Angular CLI globally..."
      - npm install -g @angular/cli

  pre_build:
    commands:
      - cd Finance-Backend
      - chmod +x mvnw
      - ./mvnw clean install -DskipTests
      - cd ../Finance-Frontend
      - npm install
      - cd ..

  build:
    commands:
      - cd Finance-Frontend
      - npm run build -- --output-path=../build/frontend
      - cd ../Finance-Backend
      - ./mvnw clean package -DskipTests
      - mkdir -p ../build/backend
      - cp target/*.jar ../build/backend/app.jar
      - cd ..

  post_build:
    commands:
      - ls -R build

artifacts:
  files:
    - frontend/**
    - backend/app.jar
    - appspec.yml
    - scripts/**
  base-directory: build
